### ISSUE TITLE
Team city script broken with TeamCity 9

### ISSUE THREAD

**Issue by dkarzon** [mmbot/mmbot.scripts#28]
Not sure if it's just me but since updating to TeamCity 9 the script has stopped working. Returning 401s from the server even though the login is correct.

Also some error messages would be good.

**Comment by dkarzon** [comment]
I will look at this sometime soon. Just wanted to see if anyone else has the same problem.

**Comment by PeteGoo** [comment]
Are you on the latest version? I moved the config to a separate file and
added an admin page because TC kept wiping the settings from main-config.xml

**Comment by dkarzon** [comment]
This is awkward...

**Comment by dkarzon** [comment]
Turns out I'm an idiot. When it said `PASSWORD` I thought it mean username. :sob: How was this working before?

**Comment by PeteGoo** [comment]
Cool. Turns out I was replying to the wrong open source project anyways. Eeeek
